using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace EliteAPI.Models.Entities.Monetization;

public enum ProductType {
	/// <summary>
	/// One-time purchase.
	/// </summary>
	Durable = 2,
	Consumable = 3,
	Subscription = 5,
	/// <summary>
	/// Generated by Discord, ignore these.
	/// </summary>
	SubscriptionGroup = 6
}

public enum ProductCategory {
	None = 0,
	Misc = 1,
	/// <summary>
	/// Background image for the bot.
	/// </summary>
	WeightImage = 2,
}

public class Product {
	[Key]
	public ulong Id { get; set; }
	
	public ProductType Type { get; set; }
	public ProductCategory Category { get; set; } = ProductCategory.None;

	[MaxLength(100)]
	public required string Name { get; set; }
	[MaxLength(128)]
	public required string Slug { get; set; }
	
	public ulong Flags { get; set; }
	
	/*
	AVAILABLE	1 << 2	SKU is available for purchase
	GUILD_SUBSCRIPTION	1 << 7	Recurring SKU that can be purchased by a user and applied to a single server. Grants access to every user in that server.
	USER_SUBSCRIPTION	1 << 8	Recurring SKU purchased by a user for themselves. Grants access to the purchasing user in every server.
	*/
	public bool IsAvailable => (Flags & 1 << 2) != 0;
	public bool IsGuildSubscription => (Flags & 1 << 7) != 0;
	public bool IsUserSubscription => (Flags & 1 << 8) != 0;
	
	public ProductFeatures? Features { get; set; }
}

[Owned]
public class ProductFeatures {
	public int? MaxMonthlyEvents { get; set; }
	public int? MaxJacobLeaderboards { get; set; }
}