name: Publish HypixelAPI

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore HypixelAPI
      
    - name: Build
      run: dotnet build --no-restore HypixelAPI -c Release
      
    - name: Publish
      run: dotnet nuget push HypixelAPI/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json